CREATE TABLE User (
USERID VARCHAR(9) NOT NULL,
UNAME VARCHAR(50) NOT NULL,
UEMAIL VARCHAR(100) NOT NULL,
UPASSWORD VARCHAR(256) NOT NULL,
PRIMARY KEY (USERID)
);

CREATE TABLE Movie (
MOVIEID VARCHAR(9) NOT NULL,
MNAME VARCHAR(50) NOT NULL,
MPOSTER VARCHAR(256) NOT NULL,
MRATING FLOAT(10) NOT NULL,
MRELEASEYEAR CHAR(4) NOT NULL,
MTRAILER VARCHAR(50) NOT NULL,
MOVERVIEW VARCHAR(500) NOT NULL,
PRIMARY KEY (MOVIEID)
);

CREATE TABLE Actor (
ACTORID VARCHAR(9) NOT NULL,
ANAME VARCHAR(256) NOT NULL,
AIMAGE VARCHAR(50) NOT NULL,
PRIMARY KEY (ACTORID)
);

CREATE TABLE Review (
REVIEWID VARCHAR(9) NOT NULL,
RBODY VARCHAR(500) NOT NULL,
RRATING FLOAT(10) NOT NULL,
RDATE DATE NOT NULL,
RUSERID VARCHAR(9) NOT NULL,
RMOVIEID VARCHAR(9) NOT NULL,
PRIMARY KEY (REVIEWID),
FOREIGN KEY(RUSERID) REFERENCES User(USERID)	
ON DELETE RESTRICT 
ON UPDATE CASCADE,
FOREIGN KEY(RMOVIEID) REFERENCES Movie(MOVIEID) 
ON DELETE RESTRICT 
ON UPDATE CASCADE
);

CREATE TABLE ActorInMovie (
MOVIEID VARCHAR(9) NOT NULL,
ACTORID VARCHAR(9) NOT NULL,
ROLENAME VARCHAR(100) NOT NULL,
PRIMARY KEY (MOVIEID,ACTORID),
FOREIGN KEY(MOVIEID) REFERENCES Movie(MOVIEID)	
ON DELETE RESTRICT 
ON UPDATE CASCADE,
FOREIGN KEY(ACTORID) REFERENCES Actor(ACTORID) 
ON DELETE RESTRICT 
ON UPDATE CASCADE
);

CREATE TABLE UserLoveMovie (
MOVIEID VARCHAR(9) NOT NULL,
USERID VARCHAR(9) NOT NULL,
PRIMARY KEY (MOVIEID,USERID),  
FOREIGN KEY(MOVIEID) REFERENCES Movie(MOVIEID)	
ON DELETE RESTRICT 
ON UPDATE CASCADE,  
FOREIGN KEY(USERID) REFERENCES User(USERID)	
ON DELETE RESTRICT 
ON UPDATE CASCADE
);

CREATE TABLE Genre (
GENREID VARCHAR(9) NOT NULL,
GNAME VARCHAR(256) NOT NULL,
PRIMARY KEY (GENREID)
);

CREATE TABLE GenreOfMovie (
MOVIEID VARCHAR(9) NOT NULL,
GENREID VARCHAR(9) NOT NULL,
PRIMARY KEY (MOVIEID,GENREID),
FOREIGN KEY(MOVIEID) REFERENCES Movie(MOVIEID)	
ON DELETE RESTRICT 
ON UPDATE CASCADE,  
FOREIGN KEY(GENREID) REFERENCES Genre(GENREID)	
ON DELETE RESTRICT 
ON UPDATE CASCADE
);

INSERT INTO `movie`(`TMDBID`, `MRELEASEYEAR`, `MTRAILER`) VALUES ("475557","2019","zAGVQLHvwOY");